version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///database/packvsfact.db
      - SECRET_KEY=packvsfact_super_secret_docker_key_2026
    volumes:
      - ./database:/app/database
      - ./ml/saved_models:/app/ml/saved_models

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
